### ISSUE TITLE
PostGIS reader usage

### ISSUE THREAD

**Issue by liquidsun** [boldtrn/graphhopper-postgis#1]
Hello!
I am really keen to try the module,
but not familiar with java development,
so provided description is insufficient for me 
to set up and use the module.
Is it possible to integrate it to the main Graphhopper
without java programming? Which config files should be altered?
Thanks for your time!

**Comment by boldtrn** [comment]
Sorry, I must have missed this issue, sorry for the late reply.

> Is it possible to integrate it to the main Graphhopper without java programming?

No sorry, it requires some Java programming.

You can have a look at [this repo](https://github.com/mbasa/graphhopper/tree/postgis), it shows how a previous version was used in GraphHopper. From there it should be relatively easy to add this plugin to GraphHopper as well. 

> Which config files should be altered?

The config.yml found in the main GraphHopper repository.

**Comment by liquidsun** [comment]
Thanks a lot for response!
